services:
  db:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: app/backend/Dockerfile
    container_name: api
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./app/backend:/app/backend
      - ./logs:/app/backend/logs # Persist logs outside container

  frontend:
    build:
      context: .
      dockerfile: app/frontend/Dockerfile
    container_name: web
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./app/frontend:/app/frontend
      - /app/frontend/node_modules

volumes:
  db-data:
