services:
  db:
    image: postgres:16-alpine
    container_name: namo_db
    ports:
      - "5433:5432" # Different port for production testing
    environment:
      POSTGRES_USER: namo_prod
      POSTGRES_PASSWORD_FILE: /run/secrets/prod_postgres_password
      POSTGRES_DB: namo_prod
    volumes:
      - db-data-prod:/var/lib/postgresql/data
    secrets:
      - prod_postgres_password
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "namo_prod", "-d", "namo_prod"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  backend:
    build:
      context: .
      dockerfile: app/backend/Dockerfile # Explicitly use production Dockerfile
    container_name: namo_backend
    ports:
      - "8001:8000" # Different port for production testing to avoid conflicts
    environment:
      # Environment
      ENVIRONMENT: production

      # Database
      POSTGRES_USER: namo_prod
      POSTGRES_DB: namo_prod
      DATABASE_HOST: db

      # FastAPI Configuration
      DEBUG: "false"
      RELOAD: "false"
      LOG_LEVEL: "info"

      # JWT Configuration
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: "15"

      # CORS Configuration
      CORS_ORIGINS: "https://namo.grabler.me"

      # Logging Configuration
      LOG_MAX_SIZE_MB: "50"
      LOG_BACKUP_COUNT: "5"
      LOG_CONSOLE: "false"
    secrets:
      - prod_postgres_password
      - prod_secret_key
      - prod_telegram_bot_token
      - prod_telegram_chat_id
    networks:
      - default
      - grabler-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  frontend:
    build:
      context: .
      dockerfile: app/frontend/Dockerfile # Explicitly use production Dockerfile
    container_name: namo_frontend
    ports:
      - "8080:80" # Use port 8080 for local testing to avoid conflicts
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Custom nginx config
    environment:
      VITE_API_URL: "https://namo.grabler.me"
      VITE_ENVIRONMENT: "production"
      VITE_APP_NAME: "Namo"
    networks:
      - default
      - grabler-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

secrets:
  prod_postgres_password:
    file: ./secrets/prod_postgres_password.txt
  prod_secret_key:
    file: ./secrets/prod_secret_key.txt
  prod_telegram_bot_token:
    file: ./secrets/telegram_bot_token.txt
  prod_telegram_chat_id:
    file: ./secrets/prod_telegram_chat_id.txt

volumes:
  db-data-prod:

networks:
  grabler-network:
    external: true
