name: Deploy to Kubernetes

on:
  push:
    branches: [main, master]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_BACKEND: ghcr.io/felixgrabler/namo/backend
  IMAGE_NAME_FRONTEND: ghcr.io/felixgrabler/namo/frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./app/backend/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME_BACKEND }}:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./app/frontend/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME_FRONTEND }}:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Create secrets
        run: |
          kubectl create secret generic namo-secrets \
            --from-literal=postgres-password="${{ secrets.POSTGRES_PASSWORD }}" \
            --from-literal=secret-key="${{ secrets.SECRET_KEY }}" \
            --namespace=namo \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/simple-deploy.yaml
          kubectl rollout restart deployment/backend -n namo
          kubectl rollout restart deployment/frontend -n namo
